CREATE DATABASE IF NOT EXISTS betacom_zadanie;
USE betacom_zadanie;

CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(36) NOT NULL,
    login VARCHAR(100) UNIQUE NOT NULL,
    password CHAR(60) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS items (
	id VARCHAR(36) NOT NULL,
    owner VARCHAR(36) NOT NULL,
    name VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (owner) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;